# -*- coding: utf-8 -*-
"""final-NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRmPmQq_ZLUKIwIommP6ujauGptsS-_N

# Multi-Agent Travel Planner

**Course:** 25CSAI05H — Natural Language Processing

This notebook runs the Multi-Agent Travel Planner system using the RealTravel dataset.

## Architecture
- **5 Specialized Agents**: Query Parser, Restaurant, Accommodation, Attraction, Planner
- **Orchestration**: LangGraph state graph with parallel search nodes
- **LLM Backend**: Groq (Llama 3.3 70B & Llama 3.1 8B)
- **Evaluation**: 5 metrics (Budget Feasibility, Constraint Satisfaction, Preference Alignment, Plan Completeness, LLM-as-Judge)
- **Experiments**: Model size comparison (8B vs 70B) and temperature variation (0.0, 0.3, 0.7)

## 1. Setup & Installation
"""

# [colab] !pip install -q --upgrade groq httpx

# ── Install all required packages ──────────────────────────────────────────
# Core: LangGraph (agent orchestration), Groq (LLM inference)
# [colab] !pip install -q groq langgraph langchain langchain-core

# Data & utilities
# [colab] !pip install -q pandas tqdm

# Section (a): Transformer fine-tuning with existing word embeddings
# [colab] !pip install -q sentence-transformers==2.7.0 transformers==4.40.0 accelerate scikit-learn

# Section (c): Learning curves & TensorBoard logging
# [colab] !pip install -q tensorboard matplotlib seaborn

import nltk
nltk.download('punkt', quiet=True)
print("All packages installed.")

import os
from groq import Groq

key = os.environ.get('GROQ_API_KEY', '')
print(f"Key set: {'YES' if key and key != 'your-groq-api-key-here' else 'NO'}")
print(f"Key starts with: {key[:15]}...")

client = Groq(api_key=key)
resp = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "Say OK"}],
    max_tokens=5,
)
print("SUCCESS:", resp.choices[0].message.content)

import os

  # Strip whitespace/newlines from the key
clean_key = os.environ.get('GROQ_API_KEY', '').strip()
os.environ['GROQ_API_KEY'] = clean_key
print(f"Clean key length: {len(clean_key)}")
print(f"Starts with: {clean_key[:15]}...")



from groq import Groq

client = Groq(api_key=clean_key)
resp = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "Say OK"}],
    max_tokens=5,
)
print("SUCCESS:", resp.choices[0].message.content)

# ── Mount Google Drive and navigate to project folder ──────────────────
import os, sys
from google.colab import drive, userdata

drive.mount('/content/drive')

# ── Set project root — adjust if your folder is named differently ───────
BASE_PATH = "/content/drive/MyDrive/PTS-master-2"
os.chdir(BASE_PATH)          # make '.' point to the project root
sys.path.insert(0, BASE_PATH)  # so 'from src.xxx import ...' works

print(f"Working directory: {os.getcwd()}")
print(f"Contents: {os.listdir('.')}")

# ── Groq API key ─────────────────────────────────────────────────────────
try:
    os.environ['GROQ_API_KEY'] = userdata.get('GROQ_API_KEY')
    print('API key loaded from Colab Secrets')
except Exception:
    os.environ['GROQ_API_KEY'] = 'YOUR_GROQ_API_KEY'.strip()   # replace with your key
    print('Using manual API key — replace with your actual key')

# Verify project structure and configuration
from src.config import validate_config, MODELS
validate_config()
print('Configuration valid!')
print(f'Available models: {list(MODELS.keys())}')
for k, v in MODELS.items():
    print(f'  {k}: {v["name"]}')

"""## 2. Load Data"""

from src.data_loader import load_all_data

data = load_all_data()

# Inspect a sample query
import json
sample_query = data['queries'][0]
print(json.dumps(sample_query, indent=2))

"""## 3. Build & Run Multi-Agent System"""

from src.graph import build_travel_planner_graph, run_travel_planner

# Build the multi-agent graph with the 70B model
graph, agents = build_travel_planner_graph(
    restaurants_df=data['restaurants'],
    accommodations_df=data['accommodations'],
    attractions_df=data['attractions'],
    attraction_summaries=data['attraction_summaries'],
    model_key='large',
    temperature=0.0,
)
print('Multi-agent graph built successfully!')

# Run on a single query
query = data['queries'][0]
print(f"Query: {query['org']} -> {query['dest']}, {query['days']} days, ${query['budget']}")
print(f"User ID: {query['user_id']}")
print()

result = run_travel_planner(graph, query)

# Display the generated plan
plan = result.get('travel_plan', {})
print(json.dumps(plan, indent=2))

"""## 4. Evaluate the Plan"""

from src.evaluate import evaluate_plan, print_evaluation_results

eval_results = evaluate_plan(
    plan=plan,
    constraints=result.get('constraints', {}),
    query_text=query.get('query', ''),
    use_llm_judge=False,
)
print_evaluation_results(eval_results)

"""## 5. Run Hyperparameter Experiments

Compare two model variations (8B vs 70B) and three temperature settings.
"""

from src.experiments import run_all_experiments

# Run experiments on 5 validation queries (increase for full evaluation)
experiment_results = run_all_experiments(
    num_samples=5,
    use_llm_judge=False,
)

"""## 5.5 Transformer Fine-Tuning — Preference Matching Model

**Assignment Section (a) — Transformer + existing word embeddings**

We fine-tune `sentence-transformers/all-MiniLM-L6-v2` (a pre-trained BERT-based Transformer with a 30 522-word vocabulary) on the RealTravel user-preference dataset.

| | **Variation 1 — Base** | **Variation 2 — Enhanced** |
|---|---|---|
| Model | all-MiniLM-L6-v2 | all-MiniLM-L6-v2 |
| Learning rate | 2e-5 | 5e-5 |
| Epochs | 3 | 5 |
| Batch size | 16 | 32 |
| Temperature | 0.7 | 1.0 |
| Max seq length | 128 | 256 |
| Vocab size | 30 522 | 30 522 |

**Training objective:** `CosineSimilarityLoss` — MSE between cosine similarity and binary label  
- Positive pair (label=1.0): user profile ↔ attraction matching their LIKES  
- Negative pair (label=0.0): user profile ↔ attraction matching their DISLIKES
"""

# ═══════════════════════════════════════════════════════════════════════
# Section (a)/(b) — Imports for fine-tuning & TensorBoard
# ═══════════════════════════════════════════════════════════════════════
import os, re, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

import torch
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter          # TensorBoard

from sentence_transformers import SentenceTransformer, InputExample, losses, util
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")

# ── Two hyperparameter configurations ────────────────────────────────────
CONFIG_V1 = {
    "name"               : "V1 — Base",
    "model_name"         : "sentence-transformers/all-MiniLM-L6-v2",
    "vocab_size"         : 30522,      # BERT WordPiece vocabulary
    "embedding_dim"      : 384,
    "learning_rate"      : 2e-5,
    "epochs"             : 3,
    "batch_size"         : 16,
    "temperature"        : 0.7,        # softmax temperature for similarity scoring
    "max_seq_length"     : 128,
    "warmup_steps"       : 50,
    "weight_decay"       : 0.01,
}

CONFIG_V2 = {
    "name"               : "V2 — Enhanced",
    "model_name"         : "sentence-transformers/all-MiniLM-L6-v2",
    "vocab_size"         : 30522,
    "embedding_dim"      : 384,
    "learning_rate"      : 5e-5,       # higher LR → faster convergence
    "epochs"             : 5,          # more epochs → better fit
    "batch_size"         : 32,         # larger batch → more stable gradients
    "temperature"        : 1.0,        # higher → more diverse preference scoring
    "max_seq_length"     : 256,        # longer context window
    "warmup_steps"       : 100,
    "weight_decay"       : 0.005,
}

print("Configurations ready.")
print(f"  V1: lr={CONFIG_V1['learning_rate']}, epochs={CONFIG_V1['epochs']}, temp={CONFIG_V1['temperature']}")
print(f"  V2: lr={CONFIG_V2['learning_rate']}, epochs={CONFIG_V2['epochs']}, temp={CONFIG_V2['temperature']}")

# ═══════════════════════════════════════════════════════════════════════
# Section (a) — Build Training Pairs from User Preference Data
# Source: profiles.jsonl (likes_top5 / dislikes_top5 per user)
#         attractions.csv  (POI descriptions)
# ═══════════════════════════════════════════════════════════════════════

def build_poi_text(row):
    """Combine attraction fields into one sentence for embedding."""
    parts = []
    if pd.notna(row.get("Name")):             parts.append(str(row["Name"]))
    if pd.notna(row.get("category")):         parts.append(f"Category: {row['category']}")
    if pd.notna(row.get("description")):      parts.append(str(row["description"])[:200])
    if pd.notna(row.get("Aggregate Rating")): parts.append(f"Rating: {row['Aggregate Rating']}")
    if pd.notna(row.get("City")):             parts.append(f"City: {row['City']}")
    return ". ".join(parts)

def build_profile_text(profile_dict):
    """Convert user likes/dislikes into a preference sentence."""
    pref     = profile_dict.get("preference", {})
    likes    = pref.get("likes_top5",    pref.get("like",    []))
    dislikes = pref.get("dislikes_top5", pref.get("dislike", []))
    text = ""
    if likes:    text += "Likes: "    + ", ".join(str(l) for l in likes[:5])    + ". "
    if dislikes: text += "Dislikes: " + ", ".join(str(d) for d in dislikes[:5]) + "."
    return text.strip() or "General traveler."

# ── Load raw files ──────────────────────────────────────────────────────
import json as _json

BASE_PATH        = "/content/drive/MyDrive/PTS-master-2"   # adjust if needed
profiles_path    = f"{BASE_PATH}/data_process/1-user_data_process/profiles.jsonl"
attractions_path = f"{BASE_PATH}/database/attractions/attractions.csv"

profiles_list = []
with open(profiles_path, "r", encoding="utf-8") as fh:
    for line in fh:
        try: profiles_list.append(_json.loads(line.strip()))
        except: pass

attract_df        = pd.read_csv(attractions_path)
attract_df["_text"] = attract_df.apply(build_poi_text, axis=1)

# ── Build positive / negative pairs ────────────────────────────────────
print("Building training pairs …")
all_examples   = []
attract_sample = attract_df.sample(min(2000, len(attract_df)), random_state=SEED)

for prof in tqdm(profiles_list[:300], desc="Pairing"):
    pref     = prof.get("preference", {})
    likes    = pref.get("likes_top5",    pref.get("like",    []))
    dislikes = pref.get("dislikes_top5", pref.get("dislike", []))
    if not likes and not dislikes: continue

    user_text = build_profile_text(prof)
    pos, neg  = 0, 0

    for _, row in attract_sample.iterrows():
        poi_text     = row["_text"].lower()
        likes_hit    = any(str(l).lower() in poi_text for l in likes    if l)
        dislikes_hit = any(str(d).lower() in poi_text for d in dislikes if d)

        if likes_hit    and pos < 3:
            all_examples.append(InputExample(texts=[user_text, row["_text"]], label=1.0))
            pos += 1
        elif dislikes_hit and neg < 3:
            all_examples.append(InputExample(texts=[user_text, row["_text"]], label=0.0))
            neg += 1
        if pos >= 3 and neg >= 3: break

random.shuffle(all_examples)
n_train        = int(len(all_examples) * 0.8)
train_examples = all_examples[:n_train]
val_examples   = all_examples[n_train:]

pos_count = sum(1 for e in all_examples if e.label == 1.0)
print(f"Total pairs : {len(all_examples)}  |  Positive: {pos_count}  |  Negative: {len(all_examples)-pos_count}")
print(f"Train: {len(train_examples)}  |  Val: {len(val_examples)}")

# Commented out IPython magic to ensure Python compatibility.
# ═══════════════════════════════════════════════════════════════════════
# Section (b)/(c) — Fine-Tuning Function with TensorBoard + Learning Curves
#
# For each epoch this function:
#   1. Trains one epoch with CosineSimilarityLoss via model.fit()
#   2. Evaluates val set → accuracy, precision, recall, F1
#   3. Approximates train loss on a 100-sample subset (cosine vs label)
#   4. Logs all scalars to TensorBoard SummaryWriter
#   5. Saves best-val-F1 checkpoint
# ═══════════════════════════════════════════════════════════════════════

import os, math, time
from torch.nn import MSELoss

def _approx_loss(model, examples, batch_size=32):
    """Compute mean CosineSimilarityLoss on a subset (no gradients)."""
    model.eval()
    criterion = MSELoss()
    losses_val = []
    subset = examples[:min(100, len(examples))]
    for i in range(0, len(subset), batch_size):
        batch = subset[i : i + batch_size]
        texts_a = [e.texts[0] for e in batch]
        texts_b = [e.texts[1] for e in batch]
        labels  = torch.tensor([e.label for e in batch], dtype=torch.float32).to(DEVICE)

        emb_a = model.encode(texts_a, convert_to_tensor=True, device=DEVICE)
        emb_b = model.encode(texts_b, convert_to_tensor=True, device=DEVICE)

        cos_sim = torch.nn.functional.cosine_similarity(emb_a, emb_b)
        loss    = criterion(cos_sim, labels)
        losses_val.append(loss.item())
    return float(np.mean(losses_val)) if losses_val else 1.0

def _eval_val(model, val_examples, threshold=0.5, temperature=1.0):
    """Predict labels on val set; return accuracy and F1."""
    if not val_examples:
        return 0.0, 0.0
    texts_a  = [e.texts[0] for e in val_examples]
    texts_b  = [e.texts[1] for e in val_examples]
    true_lbl = [int(e.label >= 0.5) for e in val_examples]

    emb_a = model.encode(texts_a, convert_to_tensor=True, device=DEVICE)
    emb_b = model.encode(texts_b, convert_to_tensor=True, device=DEVICE)
    sims  = torch.nn.functional.cosine_similarity(emb_a, emb_b)

    # Apply softmax temperature: scale logit then threshold
    scaled = (sims / temperature).sigmoid().cpu().numpy()
    pred   = (scaled >= threshold).astype(int).tolist()

    acc = accuracy_score(true_lbl, pred)
    f1  = f1_score(true_lbl, pred, zero_division=0)
    return float(acc), float(f1)


def train_model(config, train_examples, val_examples, save_root="/content/models"):
    """
    Fine-tune a SentenceTransformer config for N epochs.

    Returns:
        best_model  — SentenceTransformer at best val-F1 checkpoint
        history     — dict of lists: train_loss, val_acc, val_f1 per epoch
    """
    run_name = config["name"].replace(" ", "_").replace("—", "").strip("_")
    log_dir  = f"/content/runs/{run_name}"
    save_dir = f"{save_root}/{run_name}"
    os.makedirs(save_dir, exist_ok=True)

    writer = SummaryWriter(log_dir=log_dir)

    # ── Load fresh model for this config ──────────────────────────────
    model = SentenceTransformer(config["model_name"])
    model.max_seq_length = config["max_seq_length"]

    train_loss_fn = losses.CosineSimilarityLoss(model)
    train_loader  = DataLoader(train_examples, shuffle=True,
                               batch_size=config["batch_size"])

    history = {"train_loss": [], "val_acc": [], "val_f1": []}
    best_f1   = -1.0
    best_model = None

    print(f"\n{'─'*60}")
    print(f"Training: {config['name']}")
    print(f"  lr={config['learning_rate']} | epochs={config['epochs']} | "
          f"batch={config['batch_size']} | temp={config['temperature']}")
    print(f"  log_dir: {log_dir}")
    print(f"{'─'*60}")

    for epoch in range(1, config["epochs"] + 1):
        t0 = time.time()

        # ── Train one epoch ───────────────────────────────────────────
        model.fit(
            train_objectives=[(train_loader, train_loss_fn)],
            epochs=1,
            warmup_steps=config["warmup_steps"] if epoch == 1 else 0,
            optimizer_params={"lr": config["learning_rate"]},
            weight_decay=config["weight_decay"],
            show_progress_bar=False,
        )

        # ── Compute metrics ──────────────────────────────────────────
        t_loss = _approx_loss(model, train_examples)
        v_acc, v_f1 = _eval_val(model, val_examples,
                                 temperature=config["temperature"])

        elapsed = time.time() - t0
        history["train_loss"].append(t_loss)
        history["val_acc"].append(v_acc)
        history["val_f1"].append(v_f1)

        # ── TensorBoard logging ──────────────────────────────────────
        writer.add_scalar("Loss/Train",       t_loss, epoch)
        writer.add_scalar("Metrics/Accuracy", v_acc,  epoch)
        writer.add_scalar("Metrics/F1",       v_f1,   epoch)
        writer.flush()

        print(f"  Epoch {epoch}/{config['epochs']} | "
              f"loss={t_loss:.4f}  acc={v_acc:.3f}  F1={v_f1:.3f}  "
              f"({elapsed:.1f}s)")

        # ── Save best checkpoint ─────────────────────────────────────
        if v_f1 >= best_f1:
            best_f1   = v_f1
            best_model = model
            model.save(save_dir)

    writer.close()
    print(f"\n  Best F1={best_f1:.3f}  →  saved to {save_dir}")
    return best_model, history


# ── Launch TensorBoard (works in Colab) ─────────────────────────────────
# %load_ext tensorboard
# %tensorboard --logdir /content/runs

# ═══════════════════════════════════════════════════════════════════════
# Train Variation 1 — Base configuration
# lr=2e-5 | epochs=3 | batch=16 | temp=0.7 | max_len=128
# ═══════════════════════════════════════════════════════════════════════
model_v1, history_v1 = train_model(CONFIG_V1, train_examples, val_examples)

print("\nV1 epoch-by-epoch summary:")
for ep, (loss, acc, f1) in enumerate(
        zip(history_v1["train_loss"], history_v1["val_acc"], history_v1["val_f1"]), 1):
    print(f"  Epoch {ep}: loss={loss:.4f}  val_acc={acc:.3f}  val_F1={f1:.3f}")

# ═══════════════════════════════════════════════════════════════════════
# Train Variation 2 — Enhanced configuration
# lr=5e-5 | epochs=5 | batch=32 | temp=1.0 | max_len=256
# ═══════════════════════════════════════════════════════════════════════
model_v2, history_v2 = train_model(CONFIG_V2, train_examples, val_examples)

print("\nV2 epoch-by-epoch summary:")
for ep, (loss, acc, f1) in enumerate(
        zip(history_v2["train_loss"], history_v2["val_acc"], history_v2["val_f1"]), 1):
    print(f"  Epoch {ep}: loss={loss:.4f}  val_acc={acc:.3f}  val_F1={f1:.3f}")

# ═══════════════════════════════════════════════════════════════════════
# Section (c) — Learning Curves: V1 vs V2 side-by-side
#
# Three sub-plots: Train Loss | Val Accuracy | Val F1
# Both configurations on the same axes for direct comparison.
# ═══════════════════════════════════════════════════════════════════════

def plot_learning_curves(history_v1, history_v2, config_v1, config_v2):
    """Plot train loss and val metrics for both model configurations."""
    epochs_v1 = list(range(1, len(history_v1["train_loss"]) + 1))
    epochs_v2 = list(range(1, len(history_v2["train_loss"]) + 1))

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    fig.suptitle("Learning Curves: Fine-Tuned Preference Matching Model\n"
                 f"{config_v1['name']} vs {config_v2['name']}",
                 fontsize=14, fontweight="bold")

    # ── (1) Training Loss ──────────────────────────────────────────────
    ax = axes[0]
    ax.plot(epochs_v1, history_v1["train_loss"], "o-",  color="#2196F3",
            label=config_v1["name"], linewidth=2, markersize=7)
    ax.plot(epochs_v2, history_v2["train_loss"], "s--", color="#FF5722",
            label=config_v2["name"], linewidth=2, markersize=7)
    ax.set_title("Training Loss (CosineSimilarityLoss)", fontsize=12)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_xticks(range(1, max(len(epochs_v1), len(epochs_v2)) + 1))

    # ── (2) Validation Accuracy ───────────────────────────────────────
    ax = axes[1]
    ax.plot(epochs_v1, history_v1["val_acc"], "o-",  color="#2196F3",
            label=config_v1["name"], linewidth=2, markersize=7)
    ax.plot(epochs_v2, history_v2["val_acc"], "s--", color="#FF5722",
            label=config_v2["name"], linewidth=2, markersize=7)
    ax.set_title("Validation Accuracy", fontsize=12)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Accuracy")
    ax.set_ylim(0, 1.05)
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_xticks(range(1, max(len(epochs_v1), len(epochs_v2)) + 1))

    # ── (3) Validation F1 ─────────────────────────────────────────────
    ax = axes[2]
    ax.plot(epochs_v1, history_v1["val_f1"], "o-",  color="#2196F3",
            label=config_v1["name"], linewidth=2, markersize=7)
    ax.plot(epochs_v2, history_v2["val_f1"], "s--", color="#FF5722",
            label=config_v2["name"], linewidth=2, markersize=7)
    ax.set_title("Validation F1 Score", fontsize=12)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("F1")
    ax.set_ylim(0, 1.05)
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_xticks(range(1, max(len(epochs_v1), len(epochs_v2)) + 1))

    plt.tight_layout()
    plt.savefig("results/learning_curves.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Saved → results/learning_curves.png")

    # ── Print summary comparison table ───────────────────────────────
    print("\n" + "=" * 65)
    print(f"{'Metric':<30} {'V1 (Base)':>15} {'V2 (Enhanced)':>15}")
    print("=" * 65)
    print(f"{'Final Train Loss':<30} {history_v1['train_loss'][-1]:>15.4f} {history_v2['train_loss'][-1]:>15.4f}")
    print(f"{'Best Val Accuracy':<30} {max(history_v1['val_acc']):>15.3f} {max(history_v2['val_acc']):>15.3f}")
    print(f"{'Best Val F1':<30} {max(history_v1['val_f1']):>15.3f} {max(history_v2['val_f1']):>15.3f}")
    print(f"{'Epochs Trained':<30} {len(history_v1['train_loss']):>15d} {len(history_v2['train_loss']):>15d}")
    print("=" * 65)

import os; os.makedirs("results", exist_ok=True)
plot_learning_curves(history_v1, history_v2, CONFIG_V1, CONFIG_V2)

# ═══════════════════════════════════════════════════════════════════════
# Combined Results Dashboard
# Shows Groq multi-agent experiment scores alongside fine-tuning metrics
# ═══════════════════════════════════════════════════════════════════════

import glob, json as _json_dash

def plot_combined_results(history_v1, history_v2, config_v1, config_v2,
                          experiment_results=None):
    """
    2-row dashboard:
      Row 1: Fine-tuning learning curves (loss, accuracy, F1)
      Row 2: Groq experiment scores by config (bar chart) + F1 final comparison (bar)
    """
    fig = plt.figure(figsize=(18, 10))
    fig.suptitle("Multi-Agent Travel Planner — Full Results Dashboard",
                 fontsize=15, fontweight="bold", y=0.98)

    epochs_v1 = list(range(1, len(history_v1["train_loss"]) + 1))
    epochs_v2 = list(range(1, len(history_v2["train_loss"]) + 1))
    max_ep    = max(len(epochs_v1), len(epochs_v2))

    # ── Row 1: Learning curves ────────────────────────────────────────
    ax1 = fig.add_subplot(2, 3, 1)
    ax1.plot(epochs_v1, history_v1["train_loss"], "o-",  color="#2196F3",
             label=config_v1["name"], lw=2)
    ax1.plot(epochs_v2, history_v2["train_loss"], "s--", color="#FF5722",
             label=config_v2["name"], lw=2)
    ax1.set_title("Train Loss per Epoch")
    ax1.set_xlabel("Epoch"); ax1.set_ylabel("Loss")
    ax1.legend(fontsize=8); ax1.grid(True, alpha=0.3)
    ax1.set_xticks(range(1, max_ep + 1))

    ax2 = fig.add_subplot(2, 3, 2)
    ax2.plot(epochs_v1, history_v1["val_acc"], "o-",  color="#2196F3",
             label=config_v1["name"], lw=2)
    ax2.plot(epochs_v2, history_v2["val_acc"], "s--", color="#FF5722",
             label=config_v2["name"], lw=2)
    ax2.set_title("Val Accuracy per Epoch")
    ax2.set_xlabel("Epoch"); ax2.set_ylabel("Accuracy")
    ax2.set_ylim(0, 1.05); ax2.legend(fontsize=8); ax2.grid(True, alpha=0.3)
    ax2.set_xticks(range(1, max_ep + 1))

    ax3 = fig.add_subplot(2, 3, 3)
    ax3.plot(epochs_v1, history_v1["val_f1"], "o-",  color="#2196F3",
             label=config_v1["name"], lw=2)
    ax3.plot(epochs_v2, history_v2["val_f1"], "s--", color="#FF5722",
             label=config_v2["name"], lw=2)
    ax3.set_title("Val F1 per Epoch")
    ax3.set_xlabel("Epoch"); ax3.set_ylabel("F1")
    ax3.set_ylim(0, 1.05); ax3.legend(fontsize=8); ax3.grid(True, alpha=0.3)
    ax3.set_xticks(range(1, max_ep + 1))

    # ── Row 2: Groq experiment bar charts ─────────────────────────────
    # Try to load experiment results if not passed in
    if experiment_results is None:
        result_files = sorted(glob.glob("results/experiments_*.json"))
        if result_files:
            with open(result_files[-1]) as f:
                experiment_results = _json_dash.load(f)

    ax4 = fig.add_subplot(2, 3, 4)
    ax5 = fig.add_subplot(2, 3, 5)

    if experiment_results:
        configs      = list(experiment_results.keys())
        avg_scores   = [experiment_results[c]["aggregate"]["avg_score"]   for c in configs]
        avg_times    = [experiment_results[c]["aggregate"]["avg_time_seconds"] for c in configs]
        colors_bar   = ["#4CAF50" if "large" in c else "#FF9800" for c in configs]

        ax4.bar(range(len(configs)), avg_scores, color=colors_bar, alpha=0.85, edgecolor="black")
        ax4.set_xticks(range(len(configs)))
        ax4.set_xticklabels(configs, rotation=30, ha="right", fontsize=8)
        ax4.set_title("Groq Multi-Agent: Avg Score by Config")
        ax4.set_ylabel("Avg Aggregate Score (0–1)")
        ax4.set_ylim(0, 1.0)
        ax4.grid(axis="y", alpha=0.3)

        ax5.bar(range(len(configs)), avg_times, color=colors_bar, alpha=0.85, edgecolor="black")
        ax5.set_xticks(range(len(configs)))
        ax5.set_xticklabels(configs, rotation=30, ha="right", fontsize=8)
        ax5.set_title("Groq Multi-Agent: Avg Inference Time")
        ax5.set_ylabel("Seconds per Query")
        ax5.grid(axis="y", alpha=0.3)
    else:
        ax4.text(0.5, 0.5, "Run Section 5 first\n(experiment_results)", ha="center",
                 va="center", transform=ax4.transAxes, fontsize=11)
        ax5.text(0.5, 0.5, "No experiment data", ha="center",
                 va="center", transform=ax5.transAxes, fontsize=11)

    # ── Final comparison: fine-tuning best F1 ─────────────────────────
    ax6 = fig.add_subplot(2, 3, 6)
    names  = [config_v1["name"], config_v2["name"]]
    best_f = [max(history_v1["val_f1"]), max(history_v2["val_f1"])]
    best_a = [max(history_v1["val_acc"]), max(history_v2["val_acc"])]
    x      = [0, 1]
    ax6.bar([xi - 0.2 for xi in x], best_f, width=0.35, label="Best F1",
            color=["#2196F3", "#FF5722"], alpha=0.85, edgecolor="black")
    ax6.bar([xi + 0.2 for xi in x], best_a, width=0.35, label="Best Acc",
            color=["#90CAF9", "#FFCCBC"], alpha=0.85, edgecolor="black")
    ax6.set_xticks(x); ax6.set_xticklabels(names, fontsize=9)
    ax6.set_title("Fine-Tuning: Best Val Metrics")
    ax6.set_ylabel("Score (0–1)")
    ax6.set_ylim(0, 1.1)
    ax6.legend(fontsize=9)
    ax6.grid(axis="y", alpha=0.3)

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig("results/combined_dashboard.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Saved → results/combined_dashboard.png")

plot_combined_results(history_v1, history_v2, CONFIG_V1, CONFIG_V2,
                      experiment_results=experiment_results if 'experiment_results' in dir() else None)

"""## 6. Process Multiple Queries (Full Pipeline)"""

# Run the main pipeline on more samples
# [colab] !python -m src.main --model large --temperature 0.0 --samples 10 --split valid

"""## 7. Final Results Summary

Aggregated results from both the Groq multi-agent hyperparameter experiments (Section 5) and the sentence-transformer fine-tuning (Section 5.5).
"""

# ═══════════════════════════════════════════════════════════════════════
# Section 7 — Comprehensive Results Summary
# Prints a combined table covering:
#   (A) Groq multi-agent experiment results (model × temperature grid)
#   (B) Sentence-transformer fine-tuning metrics (V1 vs V2)
# ═══════════════════════════════════════════════════════════════════════

import glob, json as _js

print("=" * 80)
print("PART A — Groq Multi-Agent Hyperparameter Experiment Results")
print("=" * 80)

result_files = sorted(glob.glob("results/experiments_*.json"))
if result_files:
    with open(result_files[-1]) as f:
        exp_data = _js.load(f)

    print(f"\n{'Config':<25} {'Model':<30} {'Temp':>5} {'Avg Score':>10} {'Avg Time':>10} {'OK':>6}")
    print("-" * 88)
    best_name, best_score = "", -1
    for cfg_name, res in sorted(exp_data.items()):
        c = res["config"]; a = res["aggregate"]
        print(f"{cfg_name:<25} {c['model_name']:<30} {c['temperature']:>5.1f} "
              f"{a['avg_score']:>10.3f} {a['avg_time_seconds']:>8.1f}s "
              f"{a['num_successful']:>3}/{c['num_samples']}")
        if a["avg_score"] > best_score:
            best_score = a["avg_score"]; best_name = cfg_name
    print("-" * 88)
    print(f"Best config: {best_name}  (avg score = {best_score:.3f})")
else:
    print("No experiment result files found in results/. Run Section 5 first.")

# ── Part B: Fine-tuning results ───────────────────────────────────────
print("\n" + "=" * 80)
print("PART B — Sentence-Transformer Fine-Tuning Results (V1 vs V2)")
print("=" * 80)

try:
    print(f"\n{'Metric':<35} {'V1 — Base':>18} {'V2 — Enhanced':>18}")
    print("-" * 73)

    rows = [
        ("Model",          CONFIG_V1["model_name"].split("/")[-1],  CONFIG_V2["model_name"].split("/")[-1]),
        ("Learning rate",  str(CONFIG_V1["learning_rate"]),         str(CONFIG_V2["learning_rate"])),
        ("Epochs",         str(CONFIG_V1["epochs"]),                str(CONFIG_V2["epochs"])),
        ("Batch size",     str(CONFIG_V1["batch_size"]),            str(CONFIG_V2["batch_size"])),
        ("Temperature",    str(CONFIG_V1["temperature"]),           str(CONFIG_V2["temperature"])),
        ("Max seq length", str(CONFIG_V1["max_seq_length"]),        str(CONFIG_V2["max_seq_length"])),
        ("─" * 33,         "─" * 16,                                "─" * 16),
        ("Final train loss",
             f"{history_v1['train_loss'][-1]:.4f}",
             f"{history_v2['train_loss'][-1]:.4f}"),
        ("Best val accuracy",
             f"{max(history_v1['val_acc']):.3f}",
             f"{max(history_v2['val_acc']):.3f}"),
        ("Best val F1",
             f"{max(history_v1['val_f1']):.3f}",
             f"{max(history_v2['val_f1']):.3f}"),
    ]
    for label, v1, v2 in rows:
        print(f"  {label:<33} {v1:>18} {v2:>18}")

    winner = "V1 — Base" if max(history_v1["val_f1"]) >= max(history_v2["val_f1"]) else "V2 — Enhanced"
    print(f"\n  Winner (by val F1): {winner}")

except NameError:
    print("history_v1 / history_v2 not found. Run Section 5.5 fine-tuning first.")

print("\n" + "=" * 80)
print("Saved outputs: results/learning_curves.png | results/combined_dashboard.png")
print("TensorBoard logs: /content/runs/")
print("=" * 80)